/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Acer
 */
public class pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form pemesanan
     */
    public pembayaran() {
        initComponents();
        table();  
        combo();
    }
    
    private void combo(){
        try {
            Statement st = (Statement) koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM data_pelanggan");
            while(rs.next()){
                cbidpelanggan.addItem(rs.getString("id_pelanggan"));
                cbnama.addItem(rs.getString("nama"));
                cbtujuan.addItem(rs.getString("tujuan_wisata"));
            }
        } catch (Exception e) {
        }
    }
    
    public void table() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID TRANSAKSI");
        tbl.addColumn("ID PELANGGAN");
        tbl.addColumn("NAMA");
        tbl.addColumn("TUJUAN WISATA");
        tbl.addColumn("HARGA TIKET");
        
        try {
            Statement st = (Statement) koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM data_transaksi");
            
            while(rs.next()){
                tbl.addRow(new Object[]{
                    rs.getInt("id_transaksi"),
                    rs.getInt("id_pelanggan"),
                    rs.getString("nama"),
                    rs.getString("tujuan_wisata"),
                    rs.getString("harga_tiket")
                });
                tbltransaksi.setModel(tbl);
            }
            JOptionPane.showMessageDialog(null, "Koneksi ke database berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "koneksi ke database gagal" + e.getMessage());
        }
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargatiket = new javax.swing.JTextField();
        btupdate = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        btmenu = new javax.swing.JButton();
        btbayar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idtransaksi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltransaksi = new javax.swing.JTable();
        cbidpelanggan = new javax.swing.JComboBox<>();
        cbnama = new javax.swing.JComboBox<>();
        cbtujuan = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Objek Wisata Kab.Tanah Bumbu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("ID PELANGGAN          :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));

        jLabel3.setText("NAMA PELANGGAN    :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        jLabel4.setText("TUJUAN WISATA       :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));

        jLabel5.setText("HARGA TIKET            :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 224, -1, -1));

        hargatiket.setText("20.000");
        getContentPane().add(hargatiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 221, 128, -1));

        btupdate.setText("UPDATE");
        btupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btupdateMouseClicked(evt);
            }
        });
        getContentPane().add(btupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 338, -1, -1));

        btedit.setText("EDIT");
        btedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bteditMouseClicked(evt);
            }
        });
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        getContentPane().add(btedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 338, 66, -1));

        bthapus.setText("HAPUS");
        bthapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bthapusMouseClicked(evt);
            }
        });
        getContentPane().add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 338, -1, -1));

        bttambah.setText("TAMBAH");
        bttambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttambahMouseClicked(evt);
            }
        });
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        getContentPane().add(bttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 220, -1, -1));

        btkeluar.setText("KELUAR");
        btkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btkeluarMouseClicked(evt);
            }
        });
        getContentPane().add(btkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 379, -1, -1));

        btmenu.setText("MENU");
        btmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 53, 73, -1));

        btbayar.setText("PEMESANAN");
        btbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbayarActionPerformed(evt);
            }
        });
        getContentPane().add(btbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 338, -1, -1));

        jButton1.setText("CETAK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 220, -1, -1));

        jLabel6.setText("ID TRANSAKSI          :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        idtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(idtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 54, 127, -1));

        tbltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbltransaksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, 427, 59));

        getContentPane().add(cbidpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 94, 127, -1));

        cbnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnamaActionPerformed(evt);
            }
        });
        getContentPane().add(cbnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 138, 127, -1));

        getContentPane().add(cbtujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 182, 127, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
    }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_bttambahActionPerformed

    private void btmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmenuActionPerformed
        menu menu = new menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmenuActionPerformed

    private void btbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbayarActionPerformed
//         TODO add your handling code here:
        pemesanan psan = new pemesanan();
        psan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbayarActionPerformed

    private void bttambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttambahMouseClicked
        try {
            String sql = "INSERT INTO data_transaksi VALUES ('"+idtransaksi.getText()+"','"+cbidpelanggan.getSelectedItem()+"','"
                    +cbnama.getSelectedItem()+"','"+cbtujuan.getSelectedItem()+"','"+hargatiket.getText()+"')";
            Connection con = (Connection) koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "berhasil menyimpan data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bttambahMouseClicked

    private void btupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btupdateMouseClicked
        try {
            String sql = "SELECT * FROM data_transaksi WHERE id_transaksi ='"+ idtransaksi.getText() +"'";
            Connection con = (Connection) koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "berhasil mengupdate data table");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());         
        }
        table();
    }//GEN-LAST:event_btupdateMouseClicked

    private void bteditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bteditMouseClicked
        try {
            String sql = "UPDATE data_transaksi SET id_transaksi='"+idtransaksi.getText()
                    +"',id_pelanggan='"+cbidpelanggan.getSelectedItem()
                    +"',nama='"+cbnama.getSelectedItem()
                    +"',tujuan_wisata='"+cbtujuan.getSelectedItem()
                    +"',harga_tiket='"+hargatiket.getText()
                    +"' WHERE id_transaksi ='"+ idtransaksi.getText()+"'";
            Connection con = (Connection) koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasil mengedit data");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bteditMouseClicked

    private void bthapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bthapusMouseClicked
        try {
            String sql = "DELETE FROM data_transaksi WHERE id_transaksi ='"+ idtransaksi.getText() +"'";
            Connection con = (Connection) koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasil menghapus data table");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bthapusMouseClicked

    private void btkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkeluarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btkeluarMouseClicked

    private void idtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtransaksiActionPerformed

    private void tbltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltransaksiMouseClicked
        int baris = tbltransaksi.rowAtPoint(evt.getPoint());
        String id_transaksi = tbltransaksi.getValueAt(baris, 0).toString(); idtransaksi.setText(id_transaksi);
        String id_pelanggan = tbltransaksi.getValueAt(baris, 0).toString(); cbidpelanggan.setSelectedItem(id_pelanggan);
        String nama_pelanggan = tbltransaksi.getValueAt(baris, 1).toString(); cbnama.setSelectedItem(nama_pelanggan);
        String tujuan_wisata = tbltransaksi.getValueAt(baris, 2).toString(); cbtujuan.setSelectedItem(tujuan_wisata);
        String harga_tiket = tbltransaksi.getValueAt(baris, 3).toString(); hargatiket.setText(harga_tiket);
    }//GEN-LAST:event_tbltransaksiMouseClicked

    private void cbnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JasperReport reports;     
            String path = "src/reporttransaksi.jasper";
        try {
            Connection con = (Connection) koneksi.getConnection();
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint JPrint = JasperFillManager.fillReport(path, null, con);
                JasperViewer jviewer = new JasperViewer(JPrint, false);
                jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(pemesanan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(pemesanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbayar;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btmenu;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btupdate;
    private javax.swing.JComboBox<String> cbidpelanggan;
    private javax.swing.JComboBox<String> cbnama;
    private javax.swing.JComboBox<String> cbtujuan;
    private javax.swing.JTextField hargatiket;
    private javax.swing.JTextField idtransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbltransaksi;
    // End of variables declaration//GEN-END:variables
}
